export const CONTENT_LOADED = "CONTENT_LOADED";
export const LOAD_CONTENT = "LOAD_CONTENT";
export const ADD_CONTENT = "ADD_CONTENT";
export const DELETE_CONTENT = "DELETE_CONTENT";
export const GET_SINGLE_CONTENT = "GET_SINGLE_CONTENT"
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const CLICK_TO_READ = "CLICK_TO_READ";

